# Generated by Django 4.2.30 on 2026-05-28 19:46

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa obiektu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis/Atrybuty dodatkowe')),
                ('status', models.CharField(choices=[('UNDER_CARE', 'Pod opieką'), ('WITHOUT_CARE', 'Bez opieki')], default='WITHOUT_CARE', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Lokalizacja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_objects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
