# Generated by Django 4.2.30 on 2026-06-11 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feeders/')),
                ('map_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map_objects.mapobject')),
            ],
        ),
    ]
