# Generated by Django 4.2.30 on 2026-06-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_objects', '0002_mapobjectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapobject',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do transmisji na żywo'),
        ),
    ]
